/**
 * Tailwind CSS generators for theme palettes and shadcn semantic colors.
 *
 * These produce CSS strings that can be written to files at build time
 * and imported alongside `@import 'tailwindcss'`.
 */

import type { ThemesConfig } from '../types'
import { resolveThemeDesc } from '../palette-utils'
import { DEFAULT_SEEDS } from '../hanzogui/defaults/themes'

/**
 * Generate tw-theme-palettes.css content.
 *
 * Two layers per theme:
 *   1. Runtime CSS variables `--palette-{theme}-{1..12}` defined in
 *      `:root` (light) and `[data-color-scheme='dark']` (dark). The
 *      browser flips these at runtime based on the active scheme.
 *   2. A Tailwind v4 `@theme inline` block that bridges the runtime
 *      variables into Tailwind's color registry as `--color-{theme}-{N}`,
 *      so utilities like `bg-primary-9`, `text-success-9`, etc. get
 *      generated. The `inline` keyword preserves the `var(...)`
 *      reference at build time so the value actually flips at runtime.
 *
 * Example output:
 *   :root {
 *     --palette-neutral-1: #fafafa;
 *     --palette-neutral-2: #f5f5f5;
 *     ...
 *   }
 *   [data-color-scheme='dark'] {
 *     --palette-neutral-1: #0d0d0d;
 *     ...
 *   }
 *   @theme inline {
 *     --color-neutral-1: var(--palette-neutral-1);
 *     --color-neutral-2: var(--palette-neutral-2);
 *     ...
 *   }
 */
export function generateTwThemePalettesCss(config: ThemesConfig = {}): string {
  const merged = { ...DEFAULT_SEEDS, ...config }
  const themes = Object.entries(merged)

  const lightVars: string[] = []
  const darkVars: string[] = []
  const themeInlineVars: string[] = []

  for (const [name, desc] of themes) {
    const kind = name === 'neutral' ? 'neutral' : 'accent'
    const { light, dark } = resolveThemeDesc(desc, kind)
    for (let i = 0; i < 12; i++) {
      lightVars.push(`  --palette-${name}-${i + 1}: ${light[i]};`)
      darkVars.push(`  --palette-${name}-${i + 1}: ${dark[i]};`)
      themeInlineVars.push(`  --color-${name}-${i + 1}: var(--palette-${name}-${i + 1});`)
    }
  }

  return [
    '/* Generated by @hanzo/theming — do not edit manually */',
    '',
    ':root {',
    ...lightVars,
    '}',
    '',
    "[data-color-scheme='dark'] {",
    ...darkVars,
    '}',
    '',
    '@theme inline {',
    ...themeInlineVars,
    '}',
    '',
  ].join('\n')
}

/**
 * Mapping from shadcn semantic color names to palette step references.
 *
 * shadcn expects pairs like --background/--foreground, --primary/--primary-foreground, etc.
 * We map these to our 12-step palette positions:
 *
 *   Step 1–3:  backgrounds
 *   Step 4–6:  borders, muted
 *   Step 7–9:  interactive, secondary text
 *   Step 10–12: foreground text
 */
const SHADCN_LIGHT_MAP: Record<string, string> = {
  '--background':             'var(--palette-neutral-1)',
  '--foreground':             'var(--palette-neutral-11)',
  '--card':                   'var(--palette-neutral-2)',
  '--card-foreground':        'var(--palette-neutral-11)',
  '--popover':                'var(--palette-neutral-1)',
  '--popover-foreground':     'var(--palette-neutral-11)',
  '--primary':                'var(--palette-primary-10)',
  '--primary-foreground':     'var(--palette-primary-1)',
  '--secondary':              'var(--palette-neutral-3)',
  '--secondary-foreground':   'var(--palette-neutral-11)',
  '--muted':                  'var(--palette-neutral-3)',
  '--muted-foreground':       'var(--palette-neutral-8)',
  '--accent':                 'var(--palette-neutral-3)',
  '--accent-foreground':      'var(--palette-neutral-11)',
  '--destructive':            'var(--palette-danger-9)',
  '--border':                 'var(--palette-neutral-4)',
  '--input':                  'var(--palette-neutral-5)',
  '--ring':                   'var(--palette-primary-8)',
  '--chart-1':                'var(--palette-primary-8)',
  '--chart-2':                'var(--palette-success-8)',
  '--chart-3':                'var(--palette-warning-8)',
  '--chart-4':                'var(--palette-info-8)',
  '--chart-5':                'var(--palette-danger-8)',
  '--sidebar':                'var(--palette-neutral-2)',
  '--sidebar-foreground':     'var(--palette-neutral-11)',
  '--sidebar-primary':        'var(--palette-primary-10)',
  '--sidebar-primary-foreground': 'var(--palette-primary-1)',
  '--sidebar-accent':         'var(--palette-neutral-3)',
  '--sidebar-accent-foreground': 'var(--palette-neutral-11)',
  '--sidebar-border':         'var(--palette-neutral-4)',
  '--sidebar-ring':           'var(--palette-primary-8)',
}

const SHADCN_DARK_MAP: Record<string, string> = {
  '--background':             'var(--palette-neutral-1)',
  '--foreground':             'var(--palette-neutral-11)',
  '--card':                   'var(--palette-neutral-2)',
  '--card-foreground':        'var(--palette-neutral-11)',
  '--popover':                'var(--palette-neutral-2)',
  '--popover-foreground':     'var(--palette-neutral-11)',
  '--primary':                'var(--palette-primary-3)',
  '--primary-foreground':     'var(--palette-primary-12)',
  '--secondary':              'var(--palette-neutral-3)',
  '--secondary-foreground':   'var(--palette-neutral-11)',
  '--muted':                  'var(--palette-neutral-3)',
  '--muted-foreground':       'var(--palette-neutral-8)',
  '--accent':                 'var(--palette-neutral-3)',
  '--accent-foreground':      'var(--palette-neutral-11)',
  '--destructive':            'var(--palette-danger-4)',
  '--border':                 'var(--palette-neutral-4)',
  '--input':                  'var(--palette-neutral-5)',
  '--ring':                   'var(--palette-primary-5)',
  '--chart-1':                'var(--palette-primary-5)',
  '--chart-2':                'var(--palette-success-5)',
  '--chart-3':                'var(--palette-warning-5)',
  '--chart-4':                'var(--palette-info-5)',
  '--chart-5':                'var(--palette-danger-5)',
  '--sidebar':                'var(--palette-neutral-2)',
  '--sidebar-foreground':     'var(--palette-neutral-11)',
  '--sidebar-primary':        'var(--palette-primary-3)',
  '--sidebar-primary-foreground': 'var(--palette-primary-12)',
  '--sidebar-accent':         'var(--palette-neutral-3)',
  '--sidebar-accent-foreground': 'var(--palette-neutral-11)',
  '--sidebar-border':         'var(--palette-neutral-4)',
  '--sidebar-ring':           'var(--palette-primary-5)',
}

function renderVars(map: Record<string, string>): string[] {
  return Object.entries(map).map(([k, v]) => `  ${k}: ${v};`)
}

/**
 * Generate tw-shadcn-semantic-colors.css content.
 *
 * Three layers:
 *   1. `:root` and `[data-color-scheme='dark']` define semantic tokens
 *      (`--background`, `--foreground`, etc.) that point at runtime
 *      palette steps (`var(--palette-X-N)`). The palette variables
 *      themselves are defined in tw-theme-palettes.css and flip per
 *      scheme; the indirection here lets dark mode also re-route the
 *      brand-color tokens (e.g., --primary → primary-3 in dark, vs
 *      primary-10 in light) for softer accents on dark.
 *   2. `@theme {}` registers `--radius` for utility generation.
 *   3. `@theme inline {}` bridges the runtime semantic tokens into
 *      Tailwind v4's color registry as `--color-background`,
 *      `--color-foreground`, etc., so utilities like `bg-background`,
 *      `text-foreground`, `bg-card`, `border-border` actually get
 *      generated. The `inline` keyword preserves the `var(...)`
 *      reference at build time so the value flips at runtime.
 */
export function generateTwShadcnSemanticColorsCss(): string {
  const semanticInlineVars = Object.keys(SHADCN_LIGHT_MAP).map((k) => {
    const name = k.slice(2) // strip leading "--"
    return `  --color-${name}: var(${k});`
  })

  return [
    '/* Generated by @hanzo/theming — do not edit manually */',
    '',
    '@theme {',
    '  --radius: 0.625rem;',
    '}',
    '',
    '@theme inline {',
    ...semanticInlineVars,
    '}',
    '',
    ':root {',
    ...renderVars(SHADCN_LIGHT_MAP),
    '}',
    '',
    "[data-color-scheme='dark'] {",
    ...renderVars(SHADCN_DARK_MAP),
    '}',
    '',
  ].join('\n')
}
