/**
 * Tailwind CSS generators for theme palettes and shadcn semantic colors.
 *
 * These produce CSS strings that can be written to files at build time
 * and imported alongside `@import 'tailwindcss'`.
 */

import type { ThemesConfig } from '../types'
import { resolveThemeDesc } from '../palette-utils'
import { DEFAULT_SEEDS } from '../hanzogui/defaults/themes'

/**
 * Generate tw-theme-palettes.css content.
 *
 * Produces `--color-{theme}-{1..12}` custom properties for each theme
 * in both light (:root) and dark ([data-color-scheme='dark']) contexts.
 *
 * Example output:
 *   :root {
 *     --color-neutral-1: #fafafa;
 *     --color-neutral-2: #f5f5f5;
 *     ...
 *     --color-primary-1: #f9fafb;
 *     ...
 *   }
 *   [data-color-scheme='dark'] {
 *     --color-neutral-1: #0d0d0d;
 *     ...
 *   }
 */
export function generateTwThemePalettesCss(config: ThemesConfig = {}): string {
  const merged = { ...DEFAULT_SEEDS, ...config }
  const themes = Object.entries(merged)

  const lightVars: string[] = []
  const darkVars: string[] = []

  for (const [name, desc] of themes) {
    const { light, dark } = resolveThemeDesc(desc)
    for (let i = 0; i < 12; i++) {
      lightVars.push(`  --color-${name}-${i + 1}: ${light[i]};`)
      darkVars.push(`  --color-${name}-${i + 1}: ${dark[i]};`)
    }
  }

  return [
    '/* Generated by @hanzo/theming — do not edit manually */',
    '',
    ':root {',
    ...lightVars,
    '}',
    '',
    "[data-color-scheme='dark'] {",
    ...darkVars,
    '}',
    '',
  ].join('\n')
}

/**
 * Mapping from shadcn semantic color names to palette step references.
 *
 * shadcn expects pairs like --background/--foreground, --primary/--primary-foreground, etc.
 * We map these to our 12-step palette positions:
 *
 *   Step 1–3:  backgrounds
 *   Step 4–6:  borders, muted
 *   Step 7–9:  interactive, secondary text
 *   Step 10–12: foreground text
 */
const SHADCN_LIGHT_MAP: Record<string, string> = {
  '--background':             'var(--color-neutral-1)',
  '--foreground':             'var(--color-neutral-11)',
  '--card':                   'var(--color-neutral-2)',
  '--card-foreground':        'var(--color-neutral-11)',
  '--popover':                'var(--color-neutral-1)',
  '--popover-foreground':     'var(--color-neutral-11)',
  '--primary':                'var(--color-primary-10)',
  '--primary-foreground':     'var(--color-primary-1)',
  '--secondary':              'var(--color-neutral-3)',
  '--secondary-foreground':   'var(--color-neutral-11)',
  '--muted':                  'var(--color-neutral-3)',
  '--muted-foreground':       'var(--color-neutral-8)',
  '--accent':                 'var(--color-neutral-3)',
  '--accent-foreground':      'var(--color-neutral-11)',
  '--destructive':            'var(--color-danger-9)',
  '--border':                 'var(--color-neutral-4)',
  '--input':                  'var(--color-neutral-5)',
  '--ring':                   'var(--color-primary-8)',
  '--chart-1':                'var(--color-primary-8)',
  '--chart-2':                'var(--color-success-8)',
  '--chart-3':                'var(--color-warning-8)',
  '--chart-4':                'var(--color-info-8)',
  '--chart-5':                'var(--color-danger-8)',
  '--sidebar':                'var(--color-neutral-2)',
  '--sidebar-foreground':     'var(--color-neutral-11)',
  '--sidebar-primary':        'var(--color-primary-10)',
  '--sidebar-primary-foreground': 'var(--color-primary-1)',
  '--sidebar-accent':         'var(--color-neutral-3)',
  '--sidebar-accent-foreground': 'var(--color-neutral-11)',
  '--sidebar-border':         'var(--color-neutral-4)',
  '--sidebar-ring':           'var(--color-primary-8)',
}

const SHADCN_DARK_MAP: Record<string, string> = {
  '--background':             'var(--color-neutral-1)',
  '--foreground':             'var(--color-neutral-11)',
  '--card':                   'var(--color-neutral-2)',
  '--card-foreground':        'var(--color-neutral-11)',
  '--popover':                'var(--color-neutral-2)',
  '--popover-foreground':     'var(--color-neutral-11)',
  '--primary':                'var(--color-primary-3)',
  '--primary-foreground':     'var(--color-primary-12)',
  '--secondary':              'var(--color-neutral-3)',
  '--secondary-foreground':   'var(--color-neutral-11)',
  '--muted':                  'var(--color-neutral-3)',
  '--muted-foreground':       'var(--color-neutral-8)',
  '--accent':                 'var(--color-neutral-3)',
  '--accent-foreground':      'var(--color-neutral-11)',
  '--destructive':            'var(--color-danger-4)',
  '--border':                 'var(--color-neutral-4)',
  '--input':                  'var(--color-neutral-5)',
  '--ring':                   'var(--color-primary-5)',
  '--chart-1':                'var(--color-primary-5)',
  '--chart-2':                'var(--color-success-5)',
  '--chart-3':                'var(--color-warning-5)',
  '--chart-4':                'var(--color-info-5)',
  '--chart-5':                'var(--color-danger-5)',
  '--sidebar':                'var(--color-neutral-2)',
  '--sidebar-foreground':     'var(--color-neutral-11)',
  '--sidebar-primary':        'var(--color-primary-3)',
  '--sidebar-primary-foreground': 'var(--color-primary-12)',
  '--sidebar-accent':         'var(--color-neutral-3)',
  '--sidebar-accent-foreground': 'var(--color-neutral-11)',
  '--sidebar-border':         'var(--color-neutral-4)',
  '--sidebar-ring':           'var(--color-primary-5)',
}

function renderVars(map: Record<string, string>): string[] {
  return Object.entries(map).map(([k, v]) => `  ${k}: ${v};`)
}

/**
 * Generate tw-shadcn-semantic-colors.css content.
 *
 * Maps shadcn's expected CSS variable names to our palette step references.
 * The palette variables must be defined (via tw-theme-palettes.css) for these
 * to resolve.
 */
export function generateTwShadcnSemanticColorsCss(): string {
  return [
    '/* Generated by @hanzo/theming — do not edit manually */',
    '',
    ':root {',
    ...renderVars(SHADCN_LIGHT_MAP),
    '}',
    '',
    "[data-color-scheme='dark'] {",
    ...renderVars(SHADCN_DARK_MAP),
    '}',
    '',
  ].join('\n')
}
