/**
 * Palette CSS — the 12-step scales as plain custom properties.
 *
 * One `--palette-{theme}-{1..12}` variable per step, declared twice: in
 * `:root` with the light values and under `.dark` with the dark ones. The
 * browser flips the whole system by toggling that one class; nothing else
 * in the stack has to know which scheme is active.
 *
 * Plain CSS, no build step of anyone else's: no `@theme`, no `@theme inline`,
 * no utility registry. Consumers read the variables directly
 * (`background: var(--palette-primary-9)`) or through the semantic layer
 * in `./semantic`.
 */

import type { ThemesConfig } from '../types.js'
import { resolveThemeDesc } from '../palette-utils.js'
import { DEFAULT_SEEDS } from '../gui/defaults/themes.js'

/** Selector carrying the dark values. Matches `@hanzo/ui/theme.css`. */
export const DARK_SELECTOR = '.dark'

/**
 * Render the palette stylesheet for a theme config.
 *
 * Unspecified themes fall back to the default seeds, so the output always
 * defines all seven scales (neutral, primary, secondary, info, success,
 * warning, danger) and consumers never reference an undefined variable.
 */
export function generatePaletteCss(config: ThemesConfig = {}): string {
  const light: string[] = []
  const dark: string[] = []

  for (const [name, desc] of Object.entries({ ...DEFAULT_SEEDS, ...config })) {
    const scales = resolveThemeDesc(desc, name === 'neutral' ? 'neutral' : 'accent')
    for (let i = 0; i < 12; i++) {
      light.push(`  --palette-${name}-${i + 1}: ${scales.light[i]};`)
      dark.push(`  --palette-${name}-${i + 1}: ${scales.dark[i]};`)
    }
  }

  return [
    '/* Generated by @hanzo/theming — do not edit manually */',
    '',
    ':root {',
    ...light,
    '}',
    '',
    `${DARK_SELECTOR} {`,
    ...dark,
    '}',
    '',
  ].join('\n')
}
