/**
 * Semantic CSS — role names on top of the palette steps.
 *
 * `--background`, `--foreground`, `--primary`, `--border`, … each resolve to a
 * `--palette-{theme}-{step}` variable, so the whole semantic layer inherits the
 * light/dark flip from `./palettes` without restating any color.
 *
 * The dark block only carries the roles whose *step* changes on dark — softer
 * accents, a lifted popover surface. Every other role is already correct
 * because the palette variable underneath it flipped.
 *
 * Plain CSS custom properties: no `@theme`, no utility generation, no
 * framework. This is the single source for these tokens — the published
 * `semantic.css` file is emitted from it at build time.
 */

import { DARK_SELECTOR } from './palettes.js'

/** Corner radius the components round to. */
const RADIUS = '0.625rem'

/**
 * Every semantic role, at its light-scheme palette step.
 *
 * `--primary` is the seed-anchored step 9 in both schemes, so `--primary`
 * always means the brand color rather than a scheme-flipped surface.
 */
const ROLES: Record<string, string> = {
  '--background': 'var(--palette-neutral-1)',
  '--foreground': 'var(--palette-neutral-11)',
  '--card': 'var(--palette-neutral-2)',
  '--card-foreground': 'var(--palette-neutral-11)',
  '--popover': 'var(--palette-neutral-1)',
  '--popover-foreground': 'var(--palette-neutral-11)',
  '--primary': 'var(--palette-primary-9)',
  '--primary-foreground': '#fff',
  '--secondary': 'var(--palette-neutral-3)',
  '--secondary-foreground': 'var(--palette-neutral-11)',
  '--muted': 'var(--palette-neutral-3)',
  '--muted-foreground': 'var(--palette-neutral-8)',
  '--accent': 'var(--palette-neutral-3)',
  '--accent-foreground': 'var(--palette-neutral-11)',
  '--destructive': 'var(--palette-danger-9)',
  '--border': 'var(--palette-neutral-4)',
  '--input': 'var(--palette-neutral-5)',
  '--ring': 'var(--palette-primary-8)',
  '--chart-1': 'var(--palette-primary-8)',
  '--chart-2': 'var(--palette-success-8)',
  '--chart-3': 'var(--palette-warning-8)',
  '--chart-4': 'var(--palette-info-8)',
  '--chart-5': 'var(--palette-danger-8)',
  '--sidebar': 'var(--palette-neutral-2)',
  '--sidebar-foreground': 'var(--palette-neutral-11)',
  '--sidebar-primary': 'var(--palette-primary-9)',
  '--sidebar-primary-foreground': '#fff',
  '--sidebar-accent': 'var(--palette-neutral-3)',
  '--sidebar-accent-foreground': 'var(--palette-neutral-11)',
  '--sidebar-border': 'var(--palette-neutral-4)',
  '--sidebar-ring': 'var(--palette-primary-8)',
}

/** Roles that move to a different step on dark — softer accents, lifted popover. */
const DARK_OVERRIDES: Record<string, string> = {
  '--popover': 'var(--palette-neutral-2)',
  '--destructive': 'var(--palette-danger-4)',
  '--ring': 'var(--palette-primary-5)',
  '--chart-1': 'var(--palette-primary-5)',
  '--chart-2': 'var(--palette-success-5)',
  '--chart-3': 'var(--palette-warning-5)',
  '--chart-4': 'var(--palette-info-5)',
  '--chart-5': 'var(--palette-danger-5)',
  '--sidebar-ring': 'var(--palette-primary-5)',
}

const declare = (vars: Record<string, string>): string[] =>
  Object.entries(vars).map(([k, v]) => `  ${k}: ${v};`)

/**
 * Render the semantic stylesheet.
 *
 * Load it after the palette stylesheet — these tokens reference
 * `--palette-*`, which `generatePaletteCss` defines.
 */
export function generateSemanticCss(): string {
  return [
    '/* Generated by @hanzo/theming — do not edit manually */',
    '',
    ':root {',
    `  --radius: ${RADIUS};`,
    ...declare(ROLES),
    '}',
    '',
    `${DARK_SELECTOR} {`,
    ...declare(DARK_OVERRIDES),
    '}',
    '',
  ].join('\n')
}
